refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{h({l})}] - {m}{n}"
  file:
    kind: rolling_file
    path: "logs/sound-log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - [{h({l})}] - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        base: 0
        count: 10
        pattern: "logs/sound-log-{}.log"

root:
  level: info
  appenders:
    - file